"use client";

import React, { createContext, useState, useContext, ReactNode, useEffect } from 'react';
import { initialGalleryImages, GalleryImage } from '@/data/galleryImages';
import { supabase } from '@/lib/supabaseClient';

interface GalleryImageContextType {
  galleryImages: GalleryImage[];
  addGalleryImage: (image: GalleryImage) => void;
  deleteGalleryImage: (id: string) => void;
  updateGalleryImage: (updatedImage: GalleryImage) => void;
  loading: boolean; // Added loading state
}

const GalleryImageContext = createContext<GalleryImageContextType | undefined>(undefined);

export const GalleryImageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [galleryImages, setGalleryImages] = useState<GalleryImage[]>([]);
  const [loading, setLoading] = useState(true);

  // Fetch images from Supabase on mount
  const fetchImages = async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('gallery_images')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) {
        throw error;
      }

      if (data) {
        setGalleryImages(data as GalleryImage[]);
      }
    } catch (error) {
      console.error('Error fetching gallery images:', error);
      // Fallback to initial images if DB is empty or error occurs? 
      // For now, let's keep it empty or maybe show an error toast in a real app
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchImages();
  }, []);

  const addGalleryImage = async (image: GalleryImage) => {
    try {
      // Remove id if it's a temporary ID generated by frontend, let Supabase generate UUID
      // But our interface expects string. For now, we pass the object. 
      // Ideally, we should omit 'id' for insert, but let's see how the table is set up.
      // If table has default gen_random_uuid(), we can omit ID or pass undefined.
      // However, our TS type requires ID. Let's try inserting without ID by destructuring.

      const { id, ...imageWithoutId } = image;

      const { data, error } = await supabase
        .from('gallery_images')
        .insert([imageWithoutId])
        .select()
        .single();

      if (error) throw error;

      if (data) {
        setGalleryImages(prev => [data as GalleryImage, ...prev]);
      }
    } catch (error) {
      console.error('Error adding gallery image:', error);
      alert('Failed to add image. Please check console.');
    }
  };

  const deleteGalleryImage = async (id: string) => {
    try {
      const { error } = await supabase
        .from('gallery_images')
        .delete()
        .eq('id', id);

      if (error) throw error;

      setGalleryImages(prev => prev.filter(img => img.id !== id));
    } catch (error) {
      console.error('Error deleting gallery image:', error);
      alert('Failed to delete image.');
    }
  };

  const updateGalleryImage = async (updatedImage: GalleryImage) => {
    try {
      const { error } = await supabase
        .from('gallery_images')
        .update({
          src: updatedImage.src,
          alt: updatedImage.alt,
          category: updatedImage.category,
          ticker_row: updatedImage.ticker_row
        })
        .eq('id', updatedImage.id);

      if (error) throw error;

      setGalleryImages(prev =>
        prev.map(img => img.id === updatedImage.id ? updatedImage : img)
      );
    } catch (error) {
      console.error('Error updating gallery image:', error);
      alert('Failed to update image.');
    }
  };

  return (
    <GalleryImageContext.Provider value={{ galleryImages, addGalleryImage, deleteGalleryImage, updateGalleryImage, loading }}>
      {children}
    </GalleryImageContext.Provider>
  );
};

export const useGalleryImages = () => {
  const context = useContext(GalleryImageContext);
  if (context === undefined) {
    throw new Error('useGalleryImages must be used within a GalleryImageProvider');
  }
  return context;
};